[package]
name = "rk"
version = "0.1.0"
authors = ["Hugo Laloge <hugo.laloge@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
bitfield = "0.13"
lazy_static = { version = "1", features = ["spin_no_std"] }
spin = "*"
"volatile" = "0.2"
